config/routes.rb
GeekHouseGcNotifier::Application.routes.draw do
  get "sessions/callback"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    resources :users do
      resources :members
      resources :tweets
    end
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :cron_week, :cron_number_week, :message, :user_id
  belongs_to :user
  #validates_associated :user
  validates_length_of :message, maximum: 140
  validate :cron_week,        numericality: {greater_than_or_equal_to: 0,
                                              less_than_or_equal_to: 6}
  validate :cron_number_week, numericality: {greater_than_or_equal_to: 1,
                                              less_than_or_equal_to: 4}
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    authorize! :read, @user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @user = User.find(params[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= simple_form_for @user, url: user_path(@user), method: "PUT" do |f| %>
  <h3>Tweets</h3>
    <div id='tweets'>
      <% 7.times do %>
        <%= f.simple_fields_for :tweets, Tweet.new do |tweet| %>
          <%= render 'tweet_fields', f: tweet %>
        <% end %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '追加', f, :tweets %>
      </div>
    </div>
    <%= f.submit '保存' %>
<% end %>

app/views/tweets/_tweet_fields.html.erb
<div class='nested-fields'>
     <table>
        <tr>
          <td><%= f.input :message, input_html: { :cols => 50, :rows => 3 }, placeholder: "今日は普通ゴミの日だよ！！！" %></td>
          <td><%= f.input :cron_number_week, collection: {なし: 0, 第１: 1, 第２: 2, 第３: 3, 第４: 4}, default: 0 %></td>
          <td><%= f.input :cron_week, collection: {月: 1, 火: 2, 水: 3, 木: 4, 金: 5, 土: 6, 日: 0 }, default: 0 %></td>
          <td><%= link_to_remove_association "削除", f %></td>
        </tr>
      </table>
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h3>毎週つぶやかせたい事を書いてね</h3>
<p>毎日22時と、深夜2時につぶやくよ！</p>
<p>例：月曜日が「普通ゴミの日」だった場合</p>
<p>「今日は普通ゴミの日だよ！」と「月曜日」にセット。</p>
<p>結果→前日の日曜日、22時と月曜日の2時に呟いてくれるよ！</p>
<%= simple_form_for @user, url: user_path(@user), method: "PUT" do |f| %>
  <h3>つぶやき設定</h3>
    <div id='tweets'>
      <%= f.simple_fields_for :tweets do |tweet| %>
        <%= render 'tweet_fields', f: tweet %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '追加', f, :tweets %>
      </div>
    </div>
    <%= f.submit '保存' %>
    <%= hidden_field_tag :redirect_path, request.path_info %>
<% end %>
<%= link_to '戻る', user_path(@user) %>

app/views/tweets/new.html.erb
<h3>毎週つぶやかせたい事を書いてね</h3>
<p>毎日22時と、深夜2時につぶやくよ！</p>
<p>例：月曜日が「普通ゴミの日」だった場合</p>
<p>「今日は普通ゴミの日だよ！」と「月曜日」にセット。</p>
<p>結果→前日の日曜日、22時と月曜日の2時に呟いてくれるよ！</p>
<%= render 'form' %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>Cron time:</b>
  <%= @tweet.cron_time %>
</p>

<p>
  <b>User:</b>
  <%= @tweet.user_id %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>