config/routes.rb
GeekHouseGcNotifier::Application.routes.draw do
  get "sessions/callback"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    resources :users do
      resources :members
      resources :tweets
    end
  end
end

app/models/user.rb
#coding: UTF-8
class User < ActiveRecord::Base
  rolify
  has_many :members
  accepts_nested_attributes_for :members, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
  has_many :tweets
  accepts_nested_attributes_for :tweets,  reject_if: proc { |attributes| attributes['message'].blank? }, allow_destroy: true
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :trackable, :omniauthable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :password, :uid, :provider, :image,
                  :house_name, :members_attributes, :tweets_attributes,
                  :access_token, :access_secret

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.info.nickname,
                         provider:auth.provider,
                         access_token:auth.credentials.token,
                         access_secret:auth.credentials.secret,
                         uid:auth.uid,
                         password:Devise.friendly_token[0,20],
                         image:auth.info.image)
    end
    user
  end
  before_update do
    self.house_name ||= "名無しさん"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Twitter"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
#coding: UTF-8
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to users_path, :notice => "設定を適用させました。"
    else
      redirect_to params[:redirect_path], :alert => "入力項目にエラーがあり、保存できませんでした。"
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>
      </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>定期ツイートしてくれるtwitterアカウント: <%= @user.name %></p>
<%= image_tag(@user.image) %>
<% if @user.members.count.zero? %>
	<%= link_to "新規メンバー作成", new_user_member_path(@user) %>
<% else %>
	<%= link_to "メンバー編集", user_members_path(@user) %>
<% end %>
<% if @user.tweets.count.zero? %>
	<%= link_to "新規ツイート作成", new_user_tweet_path(@user) %>
<% else %>
	<%= link_to "ツイート編集", user_tweets_path(@user) %>
<% end %>