config/routes.rb
GeekHouseGcNotifier::Application.routes.draw do
  get "sessions/callback"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    resources :users do
      resources :members
      resources :tweets
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :image, :name, :turn, :user_id
  belongs_to :user
  #validates_associated :user
  validates :name, length: { maximum: 15 }
  validates :turn, presence: true, uniqueness: { scope: :user_id }

  #before_save do
  #  raise
  #end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    authorize! :read, @user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @user = User.find(params[:user_id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])
    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for @user, url: user_path(@user), method: "PUT" do |f| %>
  <h3>Member</h3>
    <div id='members'>
      <% 5.times do %>
        <%= f.simple_fields_for :members, Member.new do |member| %>
          <%= render 'member_fields', :f => member %>
        <% end %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '追加', f, :members %>
      </div>
    </div>
    <%= f.submit '保存' %>
<% end %>

app/views/members/_member_fields.html.erb
<div class='nested-fields'>
      <table>
        <tr>
          <td><%= f.input :name, placeholder: 'kitaindia' %></td>
          <td><%= f.input :turn, collection: 1..20 %></td>
          <td><%= link_to_remove_association "削除", f %></td>
        </tr>
      </table>
</div>

app/views/members/edit.html.erb
<h1>Editing member</h1>
<%= render 'form' %>

<%#= link_to 'Show', @member %> |
<%#= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h3>住人のツイッターアカウントを設定してね！</h3>

<%= simple_form_for @user, url: user_path(@user), method: "PUT" do |f| %>
  <h3>住人設定</h3>
    <div id='members'>
      <%= f.simple_fields_for :members do |member| %>
        <%= render 'member_fields', :f => member %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association '追加', f, :members %>
      </div>
    </div>
    <%= f.submit '保存' %>
    <%= hidden_field_tag :redirect_path, request.path_info %>
<% end %>
<div>
<%= link_to '戻る', user_path(@user) %>

app/views/members/new.html.erb
<h3>住人のツイッターアカウントを設定してね！</h3>
<%= render 'form' %>


<%#= simple_form_for @user, url: user_path(@user), method: "PUT" do |f| %>


<!--
  <%#= f.error_notification %>
  <%# 5.times do |i| %>
  <%#= f.fields_for :members, Member.new do |member_form| %>
    <div class="form-inputs">
      <table>
        <tr>
          <td><%#= member_form.input :name, placeholder: 'kitaindia' %></td>
          <td><%#= member_form.input :turn, collection: 1..99, selected: [i + 1] %></td>
          <td><%#= member_form.link_to_remove_association "削除", member_form %></td>
        </tr>
      </table>
      <p><%#= f.link_to_add_association "メンバーを追加", f, :members %></p>
    <%# end %>
  <%# end %>
  </div>
  <div class="form-actions">
    <%#= f.button :submit %>
  </div>
<%# end %>
</div>
-->

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Turn:</b>
  <%= @member.turn %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>